# Generated by Django 4.2.30 on 2026-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
